ops: add codecov and make improvements to dockerfiles/compose

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -15,19 +15,24 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
-      - name: Build and run docker-compose
+      - name: Start services for acceptance tests
         run: |
-          docker compose -f docker-compose.test.yml --profile acceptance build
           docker compose -f docker-compose.test.yml up -d --remove-orphans
-
-      - name: Show running containers
-        run: |
-          docker ps -a
-
-      - name: Run unit tests
-        run: |
-          docker compose -f docker-compose.test.yml exec -T app sh run_tests.sh
 
       - name: Run acceptance tests
         run: |
           docker compose -f docker-compose.test.yml --profile acceptance run --rm python-tests
+
+      - name: Run unit tests
+        run: |
+          docker compose -f docker-compose.test.yml run --rm app sh run_tests.sh
+
+      - name: DEBUG - coverage file check
+        run: cat ./coverage/coverage.out || echo "coverage.out not found"
+
+      - name: Upload coverage to Codecov
+        uses: codecov/codecov-action@v5
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }}
+          files: ./coverage/coverage.out
+          fail_ci_if_error: true
